steps:
  # Build image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-north1-docker.pkg.dev/$PROJECT_ID/pickup-locations/pickup-locations:$SHORT_SHA",
        "-t",
        "europe-north1-docker.pkg.dev/$PROJECT_ID/pickup-locations/pickup-locations:latest",
        ".",
      ]

  # Docker push to Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-north1-docker.pkg.dev/$PROJECT_ID/pickup-locations/pickup-locations:$SHORT_SHA",
      ]

  # Deploy to CloudRun
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "pickup-locations",
        "--image=europe-north1-docker.pkg.dev/$PROJECT_ID/pickup-locations/pickup-locations:$SHORT_SHA",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--service-account",
        "$_SERVICE_ACCOUNT",
        "--min-instances",
        "0",
        "--max-instances",
        "4",
        "--memory",
        "128Mi",
        "--timeout",
        "30",
      ]

images:
  - "europe-north1-docker.pkg.dev/$PROJECT_ID/pickup-locations/pickup-locations:$SHORT_SHA"
  - "europe-north1-docker.pkg.dev/$PROJECT_ID/pickup-locations/pickup-locations:latest"
